/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'HeroBuyBurnRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeroBuyBurnRouter__factory>
getContractFactory(name: 'HeroCardsMarketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeroCardsMarketplace__factory>
getContractFactory(name: 'HeroCardsV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeroCardsV2__factory>
getContractFactory(name: 'HeroCardsRewardsDistributor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeroCardsRewardsDistributor__factory>
getContractFactory(name: 'HeroCardsV2Registry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeroCardsV2Registry__factory>
getContractFactory(name: 'MockERC20ForTesting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20ForTesting__factory>
getContractFactory(name: 'MockERC721ForTesting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC721ForTesting__factory>

  getContractAt(name: 'HeroBuyBurnRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeroBuyBurnRouter>
getContractAt(name: 'HeroCardsMarketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeroCardsMarketplace>
getContractAt(name: 'HeroCardsV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeroCardsV2>
getContractAt(name: 'HeroCardsRewardsDistributor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeroCardsRewardsDistributor>
getContractAt(name: 'HeroCardsV2Registry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeroCardsV2Registry>
getContractAt(name: 'MockERC20ForTesting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20ForTesting>
getContractAt(name: 'MockERC721ForTesting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC721ForTesting>

  deployContract(name: 'HeroBuyBurnRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroBuyBurnRouter>
deployContract(name: 'HeroCardsMarketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsMarketplace>
deployContract(name: 'HeroCardsV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsV2>
deployContract(name: 'HeroCardsRewardsDistributor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsRewardsDistributor>
deployContract(name: 'HeroCardsV2Registry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsV2Registry>
deployContract(name: 'MockERC20ForTesting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20ForTesting>
deployContract(name: 'MockERC721ForTesting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC721ForTesting>

  deployContract(name: 'HeroBuyBurnRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroBuyBurnRouter>
deployContract(name: 'HeroCardsMarketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsMarketplace>
deployContract(name: 'HeroCardsV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsV2>
deployContract(name: 'HeroCardsRewardsDistributor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsRewardsDistributor>
deployContract(name: 'HeroCardsV2Registry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeroCardsV2Registry>
deployContract(name: 'MockERC20ForTesting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20ForTesting>
deployContract(name: 'MockERC721ForTesting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC721ForTesting>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  