/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HeroCardsV2Interface extends Interface {
    getFunction(nameOrSignature: "MAX_PER_WALLET" | "MAX_SUPPLY" | "acceptOwnership" | "approve" | "balanceOf" | "buyBurnRouter" | "canAccessSpinWheel" | "contractURI" | "emergencyWithdraw" | "getApproved" | "getFeeDiscount" | "getHolderTier" | "isApprovedForAll" | "isHolder" | "merkleRoot" | "mint" | "mintPhase" | "mintPrice" | "mintedPerWallet" | "name" | "owner" | "ownerOf" | "pause" | "paused" | "pendingOwner" | "provenanceHash" | "randomStartIndex" | "renounceOwnership" | "royaltyInfo" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setBaseURI" | "setBuyBurnRouter" | "setContractURI" | "setDefaultRoyalty" | "setMerkleRoot" | "setMintPhase" | "setMintPrice" | "setProvenanceHash" | "setRandomStartIndex" | "setWhitelistPrice" | "startIndexSet" | "supportsInterface" | "symbol" | "tokenByIndex" | "tokenOfOwnerByIndex" | "tokenURI" | "totalSupply" | "transferFrom" | "transferOwnership" | "unpause" | "whitelistMint" | "whitelistPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "BaseURIUpdated" | "EmergencyWithdraw" | "MerkleRootUpdated" | "MintPhaseChanged" | "Minted" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Paused" | "ProvenanceHashSet" | "RandomStartIndexSet" | "RouterUpdated" | "Transfer" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_PER_WALLET', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buyBurnRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'canAccessSpinWheel', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'contractURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFeeDiscount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getHolderTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isHolder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintedPerWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'provenanceHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'randomStartIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'royaltyInfo', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setBaseURI', values: [string]): string;
encodeFunctionData(functionFragment: 'setBuyBurnRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setContractURI', values: [string]): string;
encodeFunctionData(functionFragment: 'setDefaultRoyalty', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setMintPhase', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMintPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setProvenanceHash', values: [string]): string;
encodeFunctionData(functionFragment: 'setRandomStartIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'setWhitelistPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startIndexSet', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenByIndex', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenOfOwnerByIndex', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelistMint', values: [BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'whitelistPrice', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_PER_WALLET', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyBurnRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canAccessSpinWheel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contractURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFeeDiscount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHolderTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isHolder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintedPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provenanceHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomStartIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'royaltyInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBuyBurnRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setContractURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDefaultRoyalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProvenanceHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRandomStartIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWhitelistPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startIndexSet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenByIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOfOwnerByIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistPrice', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BaseURIUpdatedEvent {
      export type InputTuple = [newURI: string];
      export type OutputTuple = [newURI: string];
      export interface OutputObject {newURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyWithdrawEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleRootUpdatedEvent {
      export type InputTuple = [newRoot: BytesLike];
      export type OutputTuple = [newRoot: string];
      export interface OutputObject {newRoot: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintPhaseChangedEvent {
      export type InputTuple = [newPhase: BigNumberish];
      export type OutputTuple = [newPhase: bigint];
      export interface OutputObject {newPhase: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintedEvent {
      export type InputTuple = [to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [to: string, tokenId: bigint];
      export interface OutputObject {to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProvenanceHashSetEvent {
      export type InputTuple = [hash: string];
      export type OutputTuple = [hash: string];
      export interface OutputObject {hash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RandomStartIndexSetEvent {
      export type InputTuple = [index: BigNumberish];
      export type OutputTuple = [index: bigint];
      export interface OutputObject {index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RouterUpdatedEvent {
      export type InputTuple = [newRouter: AddressLike];
      export type OutputTuple = [newRouter: string];
      export interface OutputObject {newRouter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HeroCardsV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): HeroCardsV2;
    waitForDeployment(): Promise<this>;

    interface: HeroCardsV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_PER_WALLET: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    buyBurnRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    canAccessSpinWheel: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    contractURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getFeeDiscount: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getHolderTier: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isHolder: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    mintPhase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintedPerWallet: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    provenanceHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    randomStartIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    royaltyInfo: TypedContractMethod<
      [tokenId: BigNumberish, salePrice: BigNumberish, ],
      [[string, bigint] & {receiver: string, amount: bigint }],
      'view'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseURI: TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    setBuyBurnRouter: TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setContractURI: TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    setDefaultRoyalty: TypedContractMethod<
      [receiver: AddressLike, feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMerkleRoot: TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMintPhase: TypedContractMethod<
      [phase: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMintPrice: TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setProvenanceHash: TypedContractMethod<
      [hash: string, ],
      [void],
      'nonpayable'
    >
    

    
    setRandomStartIndex: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setWhitelistPrice: TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    startIndexSet: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenByIndex: TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenOfOwnerByIndex: TypedContractMethod<
      [owner: AddressLike, index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    whitelistMint: TypedContractMethod<
      [quantity: BigNumberish, proof: BytesLike[], ],
      [void],
      'payable'
    >
    

    
    whitelistPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_PER_WALLET'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyBurnRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'canAccessSpinWheel'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'contractURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getFeeDiscount'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getHolderTier'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isHolder'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'mintPhase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintedPerWallet'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'provenanceHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'randomStartIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'royaltyInfo'): TypedContractMethod<
      [tokenId: BigNumberish, salePrice: BigNumberish, ],
      [[string, bigint] & {receiver: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseURI'): TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBuyBurnRouter'): TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setContractURI'): TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDefaultRoyalty'): TypedContractMethod<
      [receiver: AddressLike, feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMerkleRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintPhase'): TypedContractMethod<
      [phase: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintPrice'): TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProvenanceHash'): TypedContractMethod<
      [hash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRandomStartIndex'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWhitelistPrice'): TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startIndexSet'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenByIndex'): TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOfOwnerByIndex'): TypedContractMethod<
      [owner: AddressLike, index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'whitelistMint'): TypedContractMethod<
      [quantity: BigNumberish, proof: BytesLike[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'whitelistPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BaseURIUpdated'): TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
getEvent(key: 'EmergencyWithdraw'): TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
getEvent(key: 'MerkleRootUpdated'): TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;
getEvent(key: 'MintPhaseChanged'): TypedContractEvent<MintPhaseChangedEvent.InputTuple, MintPhaseChangedEvent.OutputTuple, MintPhaseChangedEvent.OutputObject>;
getEvent(key: 'Minted'): TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProvenanceHashSet'): TypedContractEvent<ProvenanceHashSetEvent.InputTuple, ProvenanceHashSetEvent.OutputTuple, ProvenanceHashSetEvent.OutputObject>;
getEvent(key: 'RandomStartIndexSet'): TypedContractEvent<RandomStartIndexSetEvent.InputTuple, RandomStartIndexSetEvent.OutputTuple, RandomStartIndexSetEvent.OutputObject>;
getEvent(key: 'RouterUpdated'): TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BaseURIUpdated(string)': TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
      BaseURIUpdated: TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
    

      'EmergencyWithdraw(address,uint256)': TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
      EmergencyWithdraw: TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
    

      'MerkleRootUpdated(bytes32)': TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;
      MerkleRootUpdated: TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;
    

      'MintPhaseChanged(uint8)': TypedContractEvent<MintPhaseChangedEvent.InputTuple, MintPhaseChangedEvent.OutputTuple, MintPhaseChangedEvent.OutputObject>;
      MintPhaseChanged: TypedContractEvent<MintPhaseChangedEvent.InputTuple, MintPhaseChangedEvent.OutputTuple, MintPhaseChangedEvent.OutputObject>;
    

      'Minted(address,uint256)': TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
      Minted: TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProvenanceHashSet(string)': TypedContractEvent<ProvenanceHashSetEvent.InputTuple, ProvenanceHashSetEvent.OutputTuple, ProvenanceHashSetEvent.OutputObject>;
      ProvenanceHashSet: TypedContractEvent<ProvenanceHashSetEvent.InputTuple, ProvenanceHashSetEvent.OutputTuple, ProvenanceHashSetEvent.OutputObject>;
    

      'RandomStartIndexSet(uint256)': TypedContractEvent<RandomStartIndexSetEvent.InputTuple, RandomStartIndexSetEvent.OutputTuple, RandomStartIndexSetEvent.OutputObject>;
      RandomStartIndexSet: TypedContractEvent<RandomStartIndexSetEvent.InputTuple, RandomStartIndexSetEvent.OutputTuple, RandomStartIndexSetEvent.OutputObject>;
    

      'RouterUpdated(address)': TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;
      RouterUpdated: TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }