/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HeroBuyBurnRouterInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "emergencyWithdraw" | "getSplit" | "getSplitCount" | "owner" | "pause" | "paused" | "pendingOwner" | "renounceOwnership" | "splits" | "totalDistributed" | "totalReceived" | "transferOwnership" | "unpause" | "updateSplits"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyWithdraw" | "FundsDistributed" | "FundsReceived" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Paused" | "SplitUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSplit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSplitCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'splits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalDistributed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalReceived', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateSplits', values: [AddressLike[], BigNumberish[], string[]]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSplit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSplitCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'splits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDistributed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSplits', data: BytesLike): Result;
  }

  
    export namespace EmergencyWithdrawEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDistributedEvent {
      export type InputTuple = [totalAmount: BigNumberish];
      export type OutputTuple = [totalAmount: bigint];
      export interface OutputObject {totalAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReceivedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SplitUpdatedEvent {
      export type InputTuple = [splitCount: BigNumberish];
      export type OutputTuple = [splitCount: bigint];
      export interface OutputObject {splitCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HeroBuyBurnRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): HeroBuyBurnRouter;
    waitForDeployment(): Promise<this>;

    interface: HeroBuyBurnRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getSplit: TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint, string] & {recipient: string, bps: bigint, label: string }],
      'view'
    >
    

    
    getSplitCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    splits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string] & {recipient: string, bps: bigint, label: string }],
      'view'
    >
    

    
    totalDistributed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalReceived: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateSplits: TypedContractMethod<
      [recipients_: AddressLike[], bpsValues_: BigNumberish[], labels_: string[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getSplit'): TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint, string] & {recipient: string, bps: bigint, label: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getSplitCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'splits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string] & {recipient: string, bps: bigint, label: string }],
      'view'
    >;
getFunction(nameOrSignature: 'totalDistributed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReceived'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSplits'): TypedContractMethod<
      [recipients_: AddressLike[], bpsValues_: BigNumberish[], labels_: string[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EmergencyWithdraw'): TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
getEvent(key: 'FundsDistributed'): TypedContractEvent<FundsDistributedEvent.InputTuple, FundsDistributedEvent.OutputTuple, FundsDistributedEvent.OutputObject>;
getEvent(key: 'FundsReceived'): TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'SplitUpdated'): TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'EmergencyWithdraw(address,uint256)': TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
      EmergencyWithdraw: TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
    

      'FundsDistributed(uint256)': TypedContractEvent<FundsDistributedEvent.InputTuple, FundsDistributedEvent.OutputTuple, FundsDistributedEvent.OutputObject>;
      FundsDistributed: TypedContractEvent<FundsDistributedEvent.InputTuple, FundsDistributedEvent.OutputTuple, FundsDistributedEvent.OutputObject>;
    

      'FundsReceived(address,uint256)': TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
      FundsReceived: TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'SplitUpdated(uint256)': TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;
      SplitUpdated: TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }