/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HeroCardsRewardsDistributorInterface extends Interface {
    getFunction(nameOrSignature: "RECOVERY_DELAY" | "acceptOwnership" | "claim" | "claimed" | "createEpoch" | "epochCount" | "epochs" | "finalizeEpoch" | "heroToken" | "owner" | "pause" | "paused" | "pendingOwner" | "recoverFunds" | "renounceOwnership" | "transferOwnership" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "EpochCreated" | "EpochFinalized" | "FundsRecovered" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Paused" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'RECOVERY_DELAY', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'claimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createEpoch', values: [BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'epochCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'epochs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeEpoch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'heroToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverFunds', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'RECOVERY_DELAY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'heroToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [epochId: BigNumberish, wallet: AddressLike, nativeAmount: BigNumberish, tokenAmount: BigNumberish];
      export type OutputTuple = [epochId: bigint, wallet: string, nativeAmount: bigint, tokenAmount: bigint];
      export interface OutputObject {epochId: bigint, wallet: string, nativeAmount: bigint, tokenAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochCreatedEvent {
      export type InputTuple = [epochId: BigNumberish, merkleRoot: BytesLike, nativeAmount: BigNumberish, tokenAmount: BigNumberish];
      export type OutputTuple = [epochId: bigint, merkleRoot: string, nativeAmount: bigint, tokenAmount: bigint];
      export interface OutputObject {epochId: bigint, merkleRoot: string, nativeAmount: bigint, tokenAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochFinalizedEvent {
      export type InputTuple = [epochId: BigNumberish];
      export type OutputTuple = [epochId: bigint];
      export interface OutputObject {epochId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsRecoveredEvent {
      export type InputTuple = [epochId: BigNumberish, to: AddressLike, nativeAmount: BigNumberish, tokenAmount: BigNumberish];
      export type OutputTuple = [epochId: bigint, to: string, nativeAmount: bigint, tokenAmount: bigint];
      export interface OutputObject {epochId: bigint, to: string, nativeAmount: bigint, tokenAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HeroCardsRewardsDistributor extends BaseContract {
    
    connect(runner?: ContractRunner | null): HeroCardsRewardsDistributor;
    waitForDeployment(): Promise<this>;

    interface: HeroCardsRewardsDistributorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    RECOVERY_DELAY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [epochId: BigNumberish, nativeAmount: BigNumberish, tokenAmount: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createEpoch: TypedContractMethod<
      [merkleRoot_: BytesLike, tokenAmount_: BigNumberish, duration_: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    epochCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    epochs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {merkleRoot: string, nativeAmount: bigint, tokenAmount: bigint, claimedNative: bigint, claimedToken: bigint, startTime: bigint, endTime: bigint, finalized: boolean }],
      'view'
    >
    

    
    finalizeEpoch: TypedContractMethod<
      [epochId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    heroToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverFunds: TypedContractMethod<
      [epochId: BigNumberish, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'RECOVERY_DELAY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [epochId: BigNumberish, nativeAmount: BigNumberish, tokenAmount: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createEpoch'): TypedContractMethod<
      [merkleRoot_: BytesLike, tokenAmount_: BigNumberish, duration_: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'epochCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'epochs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {merkleRoot: string, nativeAmount: bigint, tokenAmount: bigint, claimedNative: bigint, claimedToken: bigint, startTime: bigint, endTime: bigint, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeEpoch'): TypedContractMethod<
      [epochId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'heroToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverFunds'): TypedContractMethod<
      [epochId: BigNumberish, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'EpochCreated'): TypedContractEvent<EpochCreatedEvent.InputTuple, EpochCreatedEvent.OutputTuple, EpochCreatedEvent.OutputObject>;
getEvent(key: 'EpochFinalized'): TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
getEvent(key: 'FundsRecovered'): TypedContractEvent<FundsRecoveredEvent.InputTuple, FundsRecoveredEvent.OutputTuple, FundsRecoveredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Claimed(uint256,address,uint256,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'EpochCreated(uint256,bytes32,uint256,uint256)': TypedContractEvent<EpochCreatedEvent.InputTuple, EpochCreatedEvent.OutputTuple, EpochCreatedEvent.OutputObject>;
      EpochCreated: TypedContractEvent<EpochCreatedEvent.InputTuple, EpochCreatedEvent.OutputTuple, EpochCreatedEvent.OutputObject>;
    

      'EpochFinalized(uint256)': TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
      EpochFinalized: TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
    

      'FundsRecovered(uint256,address,uint256,uint256)': TypedContractEvent<FundsRecoveredEvent.InputTuple, FundsRecoveredEvent.OutputTuple, FundsRecoveredEvent.OutputObject>;
      FundsRecovered: TypedContractEvent<FundsRecoveredEvent.InputTuple, FundsRecoveredEvent.OutputTuple, FundsRecoveredEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }