/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HeroCardsV2RegistryInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "getModule" | "getModuleInfo" | "getModuleNames" | "isModuleActive" | "owner" | "pendingOwner" | "registerModule" | "renounceOwnership" | "setModuleStatus" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ModuleRegistered" | "ModuleStatusChanged" | "ModuleUpdated" | "OwnershipTransferStarted" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'getModule', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getModuleInfo', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getModuleNames', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isModuleActive', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerModule', values: [BigNumberish, string, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setModuleStatus', values: [BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModuleInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModuleNames', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isModuleActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerModule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setModuleStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ModuleRegisteredEvent {
      export type InputTuple = [chainId: BigNumberish, name: string, addr: AddressLike, version: string];
      export type OutputTuple = [chainId: bigint, name: string, addr: string, version: string];
      export interface OutputObject {chainId: bigint, name: string, addr: string, version: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModuleStatusChangedEvent {
      export type InputTuple = [chainId: BigNumberish, name: string, newStatus: BigNumberish];
      export type OutputTuple = [chainId: bigint, name: string, newStatus: bigint];
      export interface OutputObject {chainId: bigint, name: string, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModuleUpdatedEvent {
      export type InputTuple = [chainId: BigNumberish, name: string, oldAddr: AddressLike, newAddr: AddressLike, version: string];
      export type OutputTuple = [chainId: bigint, name: string, oldAddr: string, newAddr: string, version: string];
      export interface OutputObject {chainId: bigint, name: string, oldAddr: string, newAddr: string, version: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HeroCardsV2Registry extends BaseContract {
    
    connect(runner?: ContractRunner | null): HeroCardsV2Registry;
    waitForDeployment(): Promise<this>;

    interface: HeroCardsV2RegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getModule: TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [string],
      'view'
    >
    

    
    getModuleInfo: TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [[string, bigint, string, bigint, bigint] & {addr: string, status: bigint, version: string, registeredAt: bigint, updatedAt: bigint }],
      'view'
    >
    

    
    getModuleNames: TypedContractMethod<
      [chainId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    isModuleActive: TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerModule: TypedContractMethod<
      [chainId: BigNumberish, name: string, addr: AddressLike, version: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setModuleStatus: TypedContractMethod<
      [chainId: BigNumberish, name: string, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getModule'): TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getModuleInfo'): TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [[string, bigint, string, bigint, bigint] & {addr: string, status: bigint, version: string, registeredAt: bigint, updatedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getModuleNames'): TypedContractMethod<
      [chainId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isModuleActive'): TypedContractMethod<
      [chainId: BigNumberish, name: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerModule'): TypedContractMethod<
      [chainId: BigNumberish, name: string, addr: AddressLike, version: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setModuleStatus'): TypedContractMethod<
      [chainId: BigNumberish, name: string, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ModuleRegistered'): TypedContractEvent<ModuleRegisteredEvent.InputTuple, ModuleRegisteredEvent.OutputTuple, ModuleRegisteredEvent.OutputObject>;
getEvent(key: 'ModuleStatusChanged'): TypedContractEvent<ModuleStatusChangedEvent.InputTuple, ModuleStatusChangedEvent.OutputTuple, ModuleStatusChangedEvent.OutputObject>;
getEvent(key: 'ModuleUpdated'): TypedContractEvent<ModuleUpdatedEvent.InputTuple, ModuleUpdatedEvent.OutputTuple, ModuleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ModuleRegistered(uint256,string,address,string)': TypedContractEvent<ModuleRegisteredEvent.InputTuple, ModuleRegisteredEvent.OutputTuple, ModuleRegisteredEvent.OutputObject>;
      ModuleRegistered: TypedContractEvent<ModuleRegisteredEvent.InputTuple, ModuleRegisteredEvent.OutputTuple, ModuleRegisteredEvent.OutputObject>;
    

      'ModuleStatusChanged(uint256,string,uint8)': TypedContractEvent<ModuleStatusChangedEvent.InputTuple, ModuleStatusChangedEvent.OutputTuple, ModuleStatusChangedEvent.OutputObject>;
      ModuleStatusChanged: TypedContractEvent<ModuleStatusChangedEvent.InputTuple, ModuleStatusChangedEvent.OutputTuple, ModuleStatusChangedEvent.OutputObject>;
    

      'ModuleUpdated(uint256,string,address,address,string)': TypedContractEvent<ModuleUpdatedEvent.InputTuple, ModuleUpdatedEvent.OutputTuple, ModuleUpdatedEvent.OutputObject>;
      ModuleUpdated: TypedContractEvent<ModuleUpdatedEvent.InputTuple, ModuleUpdatedEvent.OutputTuple, ModuleUpdatedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }