CREATE TABLE `influencer_mentions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tweetId` varchar(30) NOT NULL,
	`authorUsername` varchar(100) NOT NULL,
	`authorDisplayName` varchar(200),
	`authorProfileImageUrl` text,
	`authorFollowerCount` int DEFAULT 0,
	`tweetText` text NOT NULL,
	`tweetUrl` text NOT NULL,
	`tweetCreatedAt` timestamp,
	`retweetCount` int DEFAULT 0,
	`likeCount` int DEFAULT 0,
	`replyCount` int DEFAULT 0,
	`quoteCount` int DEFAULT 0,
	`mediaUrls` text,
	`mentionType` enum('direct_mention','retweet','quote','hero_tweet') NOT NULL DEFAULT 'direct_mention',
	`category` enum('influencer','community','press','partner') NOT NULL DEFAULT 'community',
	`heroMentioned` boolean DEFAULT false,
	`vetsMentioned` boolean DEFAULT false,
	`sentiment` enum('positive','neutral','negative') DEFAULT 'neutral',
	`isHighlighted` boolean DEFAULT false,
	`isHidden` boolean DEFAULT false,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `influencer_mentions_id` PRIMARY KEY(`id`),
	CONSTRAINT `influencer_mentions_tweetId_unique` UNIQUE(`tweetId`)
);
