/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20ForTesting } from './MockERC20ForTesting.js';
export type { MockERC721ForTesting } from './MockERC721ForTesting.js';