/**
 * LanguageContext — Full i18n system for HeroBase.io
 * 
 * Provides translation for all static UI text across the entire app.
 * Uses React Context + translation dictionaries instead of Google Translate
 * for 100% reliable translation of React-rendered content.
 * 
 * Supported languages: English, Español (more can be added)
 */
import { createContext, useContext, useState, useCallback, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'ja' | 'ko' | 'zh' | 'ar' | 'hi' | 'ru' | 'uk';

const STORAGE_KEY = 'hero-lang';

// Master translation dictionary
// Keys are English strings, values are translations
type TranslationDict = Record<string, string>;
type AllTranslations = Record<Language, TranslationDict>;

const translations: AllTranslations = {
  en: {}, // English is the default — no translation needed
  es: {
    // === Navigation ===
    "Swap": "Intercambiar",
    "Dashboard": "Panel",
    "Portfolio": "Portafolio",
    "DCA Orders": "Órdenes DCA",
    "Limit Orders": "Órdenes Límite",
    "Farm": "Granja",
    "Approvals": "Aprobaciones",
    "Tokenomics": "Tokenomía",
    "NFT Collection": "Colección NFT",
    "Media": "Medios",
    "Community Hub": "Centro Comunitario",
    "Explainer": "Explicación",
    "AI Assistant": "Asistente IA",
    "DAO Overview": "Resumen DAO",
    "Proposals": "Propuestas",
    "Delegates": "Delegados",
    "Treasury": "Tesorería",
    "Governance": "Gobernanza",
    "Sign In": "Iniciar Sesión",
    "Sign Out": "Cerrar Sesión",
    "Home": "Inicio",
    "Connect Wallet": "Conectar Billetera",
    "Toggle theme": "Cambiar tema",
    "Select language": "Seleccionar idioma",

    // === Home Page ===
    "Built for Veterans, by Veterans": "Construido para Veteranos, por Veteranos",
    "HERO Dapp — Built for Veterans, by Veterans": "HERO Dapp — Construido para Veteranos, por Veteranos",
    "The first DEX aggregator on PulseChain built to honor those who served.": "El primer agregador DEX en PulseChain construido para honrar a quienes sirvieron.",
    "Trade $HERO and $VETS with the best rates, lowest fees, and a mission that matters.": "Intercambia $HERO y $VETS con las mejores tasas, las tarifas más bajas y una misión que importa.",
    "Launch App": "Abrir Aplicación",
    "Learn More": "Más Información",
    "Watch Explainer": "Ver Explicación",
    "Swap Aggregator": "Agregador de Intercambio",
    "Best rates across PulseX, 9inch, Liberty Swap and more. One click, best price.": "Las mejores tasas en PulseX, 9inch, Liberty Swap y más. Un clic, mejor precio.",
    "Gasless Mode": "Modo Sin Gas",
    "Trade without gas fees. ERC-4337 Paymaster covers your transactions.": "Intercambia sin tarifas de gas. El Paymaster ERC-4337 cubre tus transacciones.",
    "Live Dashboard": "Panel en Vivo",
    "Real-time PulseChain stats: gas prices, TVL, volume, and network activity.": "Estadísticas de PulseChain en tiempo real: precios de gas, TVL, volumen y actividad de red.",
    "DCA Engine": "Motor DCA",
    "Dollar Cost Average into HERO, VETS, or any PulseChain token automatically.": "Promedio de costo en dólares en HERO, VETS o cualquier token de PulseChain automáticamente.",
    "Set your price. Walk away. Execute automatically when conditions are met.": "Establece tu precio. Aléjate. Ejecución automática cuando se cumplan las condiciones.",
    "Yield Farming": "Agricultura de Rendimiento",
    "Stake LP tokens and earn rewards. Multiple pools with competitive APY.": "Apuesta tokens LP y gana recompensas. Múltiples pools con APY competitivo.",
    "Token Approvals": "Aprobaciones de Tokens",
    "Review and revoke token approvals. Protect your wallet from exploits.": "Revisa y revoca aprobaciones de tokens. Protege tu billetera de exploits.",
    "NFT Cards": "Tarjetas NFT",
    "555 unique military trading cards. Hold to earn fee reductions and airdrops.": "555 tarjetas militares únicas. Mantén para ganar reducciones de tarifas y airdrops.",
    "Community": "Comunidad",
    "News, updates, and community content. Stay connected with the HERO ecosystem.": "Noticias, actualizaciones y contenido comunitario. Mantente conectado con el ecosistema HERO.",
    "DAO Governance": "Gobernanza DAO",
    "Vote on proposals, delegate power, and shape the future of HERO protocol.": "Vota propuestas, delega poder y da forma al futuro del protocolo HERO.",
    "Powered by": "Impulsado por",
    "PulseChain": "PulseChain",
    "BASE": "BASE",

    // === NFT Collection Page ===
    "$HERO NFT Collection": "Colección NFT $HERO",
    "555 unique cards honoring military, first responders & historical warriors worldwide": "555 tarjetas únicas honrando militares, socorristas y guerreros históricos de todo el mundo",
    "Total Cards": "Total de Tarjetas",
    "Rarity Tiers": "Niveles de Rareza",
    "Categories": "Categorías",
    "Nations": "Naciones",
    "Animated NFTs": "NFTs Animados",
    "Treasury Split": "División de Tesorería",
    "Dual-Chain Deployment": "Despliegue en Dos Cadenas",
    "555 cards split across PulseChain (~185), BASE (~185), and Shared (~185)": "555 tarjetas divididas entre PulseChain (~185), BASE (~185) y Compartidas (~185)",
    "PulseChain Primary": "PulseChain Principal",
    "BASE Secondary": "BASE Secundaria",
    "Gallery": "Galería",
    "Grail Cards": "Tarjetas Grail",
    "Rank System": "Sistema de Rangos",
    "Utility": "Utilidad",
    "Service Branches": "Ramas de Servicio",
    "Roadmap": "Hoja de Ruta",
    "Marketplace": "Mercado",
    "Military Rank Collection": "Colección de Rangos Militares",
    "Sample Artwork": "Arte de Muestra",
    "First Responder Collection": "Colección de Socorristas",
    "Common": "Común",
    "Uncommon": "Poco Común",
    "Rare": "Raro",
    "Ultra Rare": "Ultra Raro",
    "Legendary": "Legendario",
    "Epic": "Épico",
    "Mythic": "Mítico",
    "First Responder": "Socorrista",

    // === NFT Marketplace ===
    "NFT Nutters Marketplace": "Mercado NFT Nutters",
    "Browse, buy, and trade HERO NFTs on the NFT Nutters marketplace powered by SquirrelSwap. 85% of all NFT earnings go straight into the treasury wallet for charity donations. The remaining 15% is allocated towards operations, overhead, and future development of the HERO protocol.": "Explora, compra e intercambia NFTs HERO en el mercado NFT Nutters impulsado por SquirrelSwap. El 85% de todas las ganancias de NFT van directamente a la billetera de tesorería para donaciones benéficas. El 15% restante se destina a operaciones, gastos generales y desarrollo futuro del protocolo HERO.",
    "Open Full Marketplace": "Abrir Mercado Completo",

    // === Grail Cards ===
    "The 15 Grail Cards": "Las 15 Tarjetas Grail",
    "The rarest and most iconic cards in the collection. Each tells a story.": "Las tarjetas más raras e icónicas de la colección. Cada una cuenta una historia.",

    // === Rank System ===
    "NFT Rank & Utility System": "Sistema de Rangos y Utilidad NFT",
    "Your rank is determined by your HERO token holdings. Higher rank = more utility.": "Tu rango está determinado por tus tenencias de tokens HERO. Mayor rango = más utilidad.",
    "Holding Requirement": "Requisito de Tenencia",
    "Fee Reduction": "Reducción de Tarifas",

    // === Utility ===
    "NFT Utility Features": "Características de Utilidad NFT",
    "Diamond Hands Rewards": "Recompensas Manos de Diamante",
    "Governance Power": "Poder de Gobernanza",
    "Exclusive Airdrops": "Airdrops Exclusivos",
    "Staking Boost": "Impulso de Staking",
    "Rank Promotion": "Promoción de Rango",

    // === Service Branches ===
    "Supporting Veterans & First Responders": "Apoyando a Veteranos y Socorristas",
    "HERO is a 501(c)(3) nonprofit supporting military veterans and first responders through the VIC Foundation. 85% of NFT earnings go straight into the treasury wallet for charity donations. The remaining 15% is allocated towards operations, overhead, and future development of the HERO protocol.": "HERO es una organización sin fines de lucro 501(c)(3) que apoya a veteranos militares y socorristas a través de la Fundación VIC. El 85% de las ganancias de NFT van directamente a la billetera de tesorería para donaciones benéficas. El 15% restante se destina a operaciones, gastos generales y desarrollo futuro del protocolo HERO.",

    // === Roadmap ===
    "NFT Development Roadmap": "Hoja de Ruta de Desarrollo NFT",
    "In Progress": "En Progreso",
    "Planned": "Planificado",
    "Future": "Futuro",
    "Phase 1": "Fase 1",
    "Phase 2": "Fase 2",
    "Phase 3": "Fase 3",
    "Artwork & Minting": "Arte y Acuñación",
    "Utility Activation": "Activación de Utilidad",
    "Advanced Features": "Características Avanzadas",

    // === Dashboard ===
    "PulseChain Network Stats": "Estadísticas de Red PulseChain",
    "Gas Price": "Precio del Gas",
    "Block Number": "Número de Bloque",
    "Total Value Locked": "Valor Total Bloqueado",
    "24h Volume": "Volumen 24h",
    "Active Wallets": "Billeteras Activas",
    "Transactions": "Transacciones",

    // === Swap ===
    "You Pay": "Tú Pagas",
    "You Receive": "Tú Recibes",
    "Swap Tokens": "Intercambiar Tokens",
    "Max": "Máx",
    "Balance": "Saldo",
    "Price Impact": "Impacto en Precio",
    "Minimum Received": "Mínimo Recibido",
    "Route": "Ruta",
    "Slippage": "Deslizamiento",

    // === Portfolio ===
    "Your Portfolio": "Tu Portafolio",
    "Total Value": "Valor Total",
    "Assets": "Activos",
    "Token": "Token",
    "Price": "Precio",
    "Amount": "Cantidad",
    "Value": "Valor",
    "24h Change": "Cambio 24h",

    // === Farm ===
    "Yield Farms": "Granjas de Rendimiento",
    "Stake": "Apostar",
    "Unstake": "Retirar",
    "Harvest": "Cosechar",
    "APY": "APY",
    "TVL": "TVL",
    "Your Stake": "Tu Apuesta",
    "Earned": "Ganado",

    // === DCA ===
    "DCA Strategy": "Estrategia DCA",
    "Create DCA Order": "Crear Orden DCA",
    "Frequency": "Frecuencia",
    "Amount per Order": "Cantidad por Orden",
    "Total Orders": "Total de Órdenes",
    "Active": "Activo",
    "Completed": "Completado",
    "Cancelled": "Cancelado",
    "Daily": "Diario",
    "Weekly": "Semanal",
    "Monthly": "Mensual",

    // === Tokenomics ===
    "Token Distribution": "Distribución de Tokens",
    "Total Supply": "Suministro Total",
    "Circulating Supply": "Suministro Circulante",
    "Burned": "Quemado",
    "Liquidity Pool": "Pool de Liquidez",
    "Contract Address": "Dirección del Contrato",
    "Buy Tax": "Impuesto de Compra",
    "Sell Tax": "Impuesto de Venta",

    // === DAO ===
    "Active Proposals": "Propuestas Activas",
    "Create Proposal": "Crear Propuesta",
    "Vote": "Votar",
    "For": "A Favor",
    "Against": "En Contra",
    "Abstain": "Abstención",
    "Quorum": "Quórum",
    "Voting Power": "Poder de Voto",
    "Delegate": "Delegar",
    "Your Delegates": "Tus Delegados",
    "Treasury Balance": "Saldo de Tesorería",

    // === Media / Blog ===
    "Latest News": "Últimas Noticias",
    "Read More": "Leer Más",
    "Published": "Publicado",
    "Share": "Compartir",

    // === AI Assistant ===
    "Ask anything about HERO, PulseChain, or DeFi": "Pregunta cualquier cosa sobre HERO, PulseChain o DeFi",
    "Type your message...": "Escribe tu mensaje...",
    "Send": "Enviar",

    // === Common UI ===
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Close": "Cerrar",
    "Back": "Atrás",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "Copy": "Copiar",
    "Copied!": "¡Copiado!",
    "View All": "Ver Todo",
    "Show More": "Mostrar Más",
    "Show Less": "Mostrar Menos",
    "No results found": "No se encontraron resultados",
    "Feature coming soon": "Función próximamente",
    "VERIFIED BY SPYWOLF": "VERIFICADO POR SPYWOLF",
    "AUDITED": "AUDITADO",
    "KYC VERIFIED": "KYC VERIFICADO",
    "KYC": "KYC",

    // === Footer ===
    "85% of NFT earnings go straight into the treasury wallet for charity donations. The remaining 15% is allocated towards operations, overhead, and future development of the HERO protocol.": "El 85% de las ganancias de NFT van directamente a la billetera de tesorería para donaciones benéficas. El 15% restante se destina a operaciones, gastos generales y desarrollo futuro del protocolo HERO.",

    // === Explainer ===
    "What is HERO?": "¿Qué es HERO?",
    "How to Buy": "Cómo Comprar",
    "Getting Started": "Primeros Pasos",
  },
  // Stub entries for other languages — can be filled in later
  fr: {
    "Swap": "Échanger",
    "Dashboard": "Tableau de Bord",
    "Portfolio": "Portefeuille",
    "DCA Orders": "Ordres DCA",
    "Limit Orders": "Ordres Limites",
    "Farm": "Ferme",
    "Approvals": "Approbations",
    "Tokenomics": "Tokenomique",
    "NFT Collection": "Collection NFT",
    "Media": "Médias",
    "Community Hub": "Centre Communautaire",
    "Explainer": "Explications",
    "AI Assistant": "Assistant IA",
    "DAO Overview": "Aperçu DAO",
    "Proposals": "Propositions",
    "Delegates": "Délégués",
    "Treasury": "Trésorerie",
    "Governance": "Gouvernance",
    "Sign In": "Se Connecter",
    "Sign Out": "Se Déconnecter",
    "Home": "Accueil",
    "Connect Wallet": "Connecter le Portefeuille",
    "Toggle theme": "Changer le thème",
    "Select language": "Sélectionner la langue",
    "Built for Veterans, by Veterans": "Construit pour les Vétérans, par des Vétérans",
    "HERO Dapp — Built for Veterans, by Veterans": "HERO Dapp — Construit pour les Vétérans, par des Vétérans",
    "The first DEX aggregator on PulseChain built to honor those who served.": "Le premier agrégateur DEX sur PulseChain construit pour honorer ceux qui ont servi.",
    "Trade $HERO and $VETS with the best rates, lowest fees, and a mission that matters.": "Échangez $HERO et $VETS aux meilleurs taux, frais les plus bas, et une mission qui compte.",
    "Launch App": "Lancer l'Application",
    "Learn More": "En Savoir Plus",
    "Watch Explainer": "Voir l'Explication",
    "Swap Aggregator": "Agrégateur d'Échange",
    "Best rates across PulseX, 9inch, Liberty Swap and more. One click, best price.": "Les meilleurs taux sur PulseX, 9inch, Liberty Swap et plus. Un clic, meilleur prix.",
    "Gasless Mode": "Mode Sans Frais de Gas",
    "Trade without gas fees. ERC-4337 Paymaster covers your transactions.": "Échangez sans frais de gas. Le Paymaster ERC-4337 couvre vos transactions.",
    "Live Dashboard": "Tableau de Bord en Direct",
    "Real-time PulseChain stats: gas prices, TVL, volume, and network activity.": "Statistiques PulseChain en temps réel : prix du gas, TVL, volume et activité réseau.",
    "DCA Engine": "Moteur DCA",
    "Dollar Cost Average into HERO, VETS, or any PulseChain token automatically.": "Investissement programmé dans HERO, VETS ou tout token PulseChain automatiquement.",
    "Set your price. Walk away. Execute automatically when conditions are met.": "Fixez votre prix. Partez. Exécution automatique lorsque les conditions sont remplies.",
    "Yield Farming": "Agriculture de Rendement",
    "Stake LP tokens and earn rewards. Multiple pools with competitive APY.": "Stakez des tokens LP et gagnez des récompenses. Plusieurs pools avec APY compétitif.",
    "Token Approvals": "Approbations de Tokens",
    "Review and revoke token approvals. Protect your wallet from exploits.": "Vérifiez et révoquez les approbations de tokens. Protégez votre portefeuille.",
    "NFT Cards": "Cartes NFT",
    "555 unique military trading cards. Hold to earn fee reductions and airdrops.": "555 cartes militaires uniques. Détenez pour gagner des réductions et des airdrops.",
    "Community": "Communauté",
    "News, updates, and community content. Stay connected with the HERO ecosystem.": "Actualités, mises à jour et contenu communautaire. Restez connecté à l'écosystème HERO.",
    "DAO Governance": "Gouvernance DAO",
    "Vote on proposals, delegate power, and shape the future of HERO protocol.": "Votez les propositions, déléguez le pouvoir et façonnez l'avenir du protocole HERO.",
    "Powered by": "Propulsé par",
    "$HERO NFT Collection": "Collection NFT $HERO",
    "555 unique cards honoring military, first responders & historical warriors worldwide": "555 cartes uniques honorant militaires, premiers intervenants et guerriers historiques du monde entier",
    "Total Cards": "Total de Cartes",
    "Rarity Tiers": "Niveaux de Rareté",
    "Categories": "Catégories",
    "Nations": "Nations",
    "Animated NFTs": "NFTs Animés",
    "Treasury Split": "Répartition de la Trésorerie",
    "Dual-Chain Deployment": "Déploiement Double Chaîne",
    "555 cards split across PulseChain (~185), BASE (~185), and Shared (~185)": "555 cartes réparties entre PulseChain (~185), BASE (~185) et Partagées (~185)",
    "PulseChain Primary": "PulseChain Principal",
    "BASE Secondary": "BASE Secondaire",
    "Gallery": "Galerie",
    "Grail Cards": "Cartes Grail",
    "Rank System": "Système de Rangs",
    "Utility": "Utilité",
    "Service Branches": "Branches de Service",
    "Roadmap": "Feuille de Route",
    "Marketplace": "Marché",
    "Military Rank Collection": "Collection de Rangs Militaires",
    "Sample Artwork": "Exemples d'Art",
    "First Responder Collection": "Collection Premiers Intervenants",
    "Common": "Commun",
    "Uncommon": "Peu Commun",
    "Rare": "Rare",
    "Ultra Rare": "Ultra Rare",
    "Legendary": "Légendaire",
    "Epic": "Épique",
    "Mythic": "Mythique",
    "First Responder": "Premier Intervenant",
    "NFT Nutters Marketplace": "Marché NFT Nutters",
    "Open Full Marketplace": "Ouvrir le Marché Complet",
    "The 15 Grail Cards": "Les 15 Cartes Grail",
    "NFT Rank & Utility System": "Système de Rangs et Utilité NFT",
    "Holding Requirement": "Exigence de Détention",
    "Fee Reduction": "Réduction des Frais",
    "NFT Utility Features": "Fonctionnalités d'Utilité NFT",
    "Diamond Hands Rewards": "Récompenses Mains de Diamant",
    "Governance Power": "Pouvoir de Gouvernance",
    "Exclusive Airdrops": "Airdrops Exclusifs",
    "Staking Boost": "Boost de Staking",
    "Rank Promotion": "Promotion de Rang",
    "Supporting Veterans & First Responders": "Soutien aux Vétérans et Premiers Intervenants",
    "NFT Development Roadmap": "Feuille de Route de Développement NFT",
    "In Progress": "En Cours",
    "Planned": "Planifié",
    "Future": "Futur",
    "Phase 1": "Phase 1",
    "Phase 2": "Phase 2",
    "Phase 3": "Phase 3",
    "Artwork & Minting": "Art et Frappe",
    "Utility Activation": "Activation de l'Utilité",
    "Advanced Features": "Fonctionnalités Avancées",
    "PulseChain Network Stats": "Statistiques du Réseau PulseChain",
    "Gas Price": "Prix du Gas",
    "Block Number": "Numéro de Bloc",
    "Total Value Locked": "Valeur Totale Verrouillée",
    "24h Volume": "Volume 24h",
    "Active Wallets": "Portefeuilles Actifs",
    "Transactions": "Transactions",
    "You Pay": "Vous Payez",
    "You Receive": "Vous Recevez",
    "Swap Tokens": "Échanger des Tokens",
    "Max": "Max",
    "Balance": "Solde",
    "Price Impact": "Impact sur le Prix",
    "Minimum Received": "Minimum Reçu",
    "Route": "Route",
    "Slippage": "Glissement",
    "Your Portfolio": "Votre Portefeuille",
    "Total Value": "Valeur Totale",
    "Assets": "Actifs",
    "Token": "Token",
    "Price": "Prix",
    "Amount": "Montant",
    "Value": "Valeur",
    "24h Change": "Variation 24h",
    "Yield Farms": "Fermes de Rendement",
    "Stake": "Staker",
    "Unstake": "Retirer",
    "Harvest": "Récolter",
    "APY": "APY",
    "TVL": "TVL",
    "Your Stake": "Votre Stake",
    "Earned": "Gagné",
    "DCA Strategy": "Stratégie DCA",
    "Create DCA Order": "Créer un Ordre DCA",
    "Frequency": "Fréquence",
    "Amount per Order": "Montant par Ordre",
    "Total Orders": "Total des Ordres",
    "Active": "Actif",
    "Completed": "Terminé",
    "Cancelled": "Annulé",
    "Daily": "Quotidien",
    "Weekly": "Hebdomadaire",
    "Monthly": "Mensuel",
    "Token Distribution": "Distribution des Tokens",
    "Total Supply": "Offre Totale",
    "Circulating Supply": "Offre en Circulation",
    "Burned": "Brûlé",
    "Liquidity Pool": "Pool de Liquidité",
    "Contract Address": "Adresse du Contrat",
    "Buy Tax": "Taxe d'Achat",
    "Sell Tax": "Taxe de Vente",
    "Active Proposals": "Propositions Actives",
    "Create Proposal": "Créer une Proposition",
    "Vote": "Voter",
    "For": "Pour",
    "Against": "Contre",
    "Abstain": "Abstention",
    "Quorum": "Quorum",
    "Voting Power": "Pouvoir de Vote",
    "Delegate": "Déléguer",
    "Your Delegates": "Vos Délégués",
    "Treasury Balance": "Solde de Trésorerie",
    "Latest News": "Dernières Nouvelles",
    "Read More": "Lire Plus",
    "Published": "Publié",
    "Share": "Partager",
    "Ask anything about HERO, PulseChain, or DeFi": "Posez toute question sur HERO, PulseChain ou DeFi",
    "Type your message...": "Tapez votre message...",
    "Send": "Envoyer",
    "Loading...": "Chargement...",
    "Error": "Erreur",
    "Success": "Succès",
    "Cancel": "Annuler",
    "Confirm": "Confirmer",
    "Close": "Fermer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Sort": "Trier",
    "Copy": "Copier",
    "Copied!": "Copié !",
    "View All": "Voir Tout",
    "Show More": "Afficher Plus",
    "Show Less": "Afficher Moins",
    "No results found": "Aucun résultat trouvé",
    "Feature coming soon": "Fonctionnalité à venir",
    "VERIFIED BY SPYWOLF": "VÉRIFIÉ PAR SPYWOLF",
    "AUDITED": "AUDITÉ",
    "KYC VERIFIED": "KYC VÉRIFIÉ",
    "KYC": "KYC",
    "What is HERO?": "Qu'est-ce que HERO ?",
    "How to Buy": "Comment Acheter",
    "Getting Started": "Premiers Pas",
    "PulseChain": "PulseChain",
    "BASE": "BASE",
  },
  de: {
    "Swap": "Tauschen",
    "Dashboard": "Übersicht",
    "Portfolio": "Portfolio",
    "DCA Orders": "DCA-Aufträge",
    "Limit Orders": "Limit-Aufträge",
    "Farm": "Farm",
    "Approvals": "Genehmigungen",
    "Tokenomics": "Tokenomics",
    "NFT Collection": "NFT-Sammlung",
    "Media": "Medien",
    "Community Hub": "Community-Zentrum",
    "Explainer": "Erklärung",
    "AI Assistant": "KI-Assistent",
    "DAO Overview": "DAO-Übersicht",
    "Proposals": "Vorschläge",
    "Delegates": "Delegierte",
    "Treasury": "Schatzkammer",
    "Governance": "Governance",
    "Sign In": "Anmelden",
    "Sign Out": "Abmelden",
    "Home": "Startseite",
    "Connect Wallet": "Wallet Verbinden",
    "Toggle theme": "Thema wechseln",
    "Select language": "Sprache wählen",
    "Built for Veterans, by Veterans": "Von Veteranen für Veteranen gebaut",
    "HERO Dapp — Built for Veterans, by Veterans": "HERO Dapp — Von Veteranen für Veteranen gebaut",
    "The first DEX aggregator on PulseChain built to honor those who served.": "Der erste DEX-Aggregator auf PulseChain, gebaut um diejenigen zu ehren, die gedient haben.",
    "Trade $HERO and $VETS with the best rates, lowest fees, and a mission that matters.": "Handeln Sie $HERO und $VETS mit den besten Kursen, niedrigsten Gebühren und einer Mission, die zählt.",
    "Launch App": "App Starten",
    "Learn More": "Mehr Erfahren",
    "Watch Explainer": "Erklärung Ansehen",
    "Swap Aggregator": "Tausch-Aggregator",
    "Best rates across PulseX, 9inch, Liberty Swap and more. One click, best price.": "Beste Kurse über PulseX, 9inch, Liberty Swap und mehr. Ein Klick, bester Preis.",
    "Gasless Mode": "Gasfreier Modus",
    "Trade without gas fees. ERC-4337 Paymaster covers your transactions.": "Handeln ohne Gasgebühren. Der ERC-4337 Paymaster übernimmt Ihre Transaktionen.",
    "Live Dashboard": "Live-Übersicht",
    "Real-time PulseChain stats: gas prices, TVL, volume, and network activity.": "PulseChain-Statistiken in Echtzeit: Gaspreise, TVL, Volumen und Netzwerkaktivität.",
    "DCA Engine": "DCA-Motor",
    "Dollar Cost Average into HERO, VETS, or any PulseChain token automatically.": "Automatischer Durchschnittskosteneffekt in HERO, VETS oder jeden PulseChain-Token.",
    "Set your price. Walk away. Execute automatically when conditions are met.": "Setzen Sie Ihren Preis. Gehen Sie. Automatische Ausführung wenn Bedingungen erfüllt sind.",
    "Yield Farming": "Ertragslandwirtschaft",
    "Stake LP tokens and earn rewards. Multiple pools with competitive APY.": "Staken Sie LP-Token und verdienen Sie Belohnungen. Mehrere Pools mit wettbewerbsfähigem APY.",
    "Token Approvals": "Token-Genehmigungen",
    "Review and revoke token approvals. Protect your wallet from exploits.": "Überprüfen und widerrufen Sie Token-Genehmigungen. Schützen Sie Ihre Wallet.",
    "NFT Cards": "NFT-Karten",
    "555 unique military trading cards. Hold to earn fee reductions and airdrops.": "555 einzigartige Militär-Sammelkarten. Halten für Gebührenreduzierungen und Airdrops.",
    "Community": "Gemeinschaft",
    "News, updates, and community content. Stay connected with the HERO ecosystem.": "Nachrichten, Updates und Community-Inhalte. Bleiben Sie mit dem HERO-Ökosystem verbunden.",
    "DAO Governance": "DAO-Governance",
    "Vote on proposals, delegate power, and shape the future of HERO protocol.": "Stimmen Sie über Vorschläge ab, delegieren Sie Macht und gestalten Sie die Zukunft des HERO-Protokolls.",
    "Powered by": "Betrieben von",
    "$HERO NFT Collection": "$HERO NFT-Sammlung",
    "555 unique cards honoring military, first responders & historical warriors worldwide": "555 einzigartige Karten zu Ehren von Militär, Ersthelfer und historischen Kriegern weltweit",
    "Total Cards": "Gesamtkarten",
    "Rarity Tiers": "Seltenheitsstufen",
    "Categories": "Kategorien",
    "Nations": "Nationen",
    "Animated NFTs": "Animierte NFTs",
    "Treasury Split": "Schatzkammer-Aufteilung",
    "Dual-Chain Deployment": "Dual-Chain-Bereitstellung",
    "Gallery": "Galerie",
    "Grail Cards": "Grail-Karten",
    "Rank System": "Rangsystem",
    "Utility": "Nutzen",
    "Service Branches": "Dienstzweige",
    "Roadmap": "Fahrplan",
    "Marketplace": "Marktplatz",
    "Military Rank Collection": "Militärrang-Sammlung",
    "Sample Artwork": "Beispielkunstwerke",
    "First Responder Collection": "Ersthelfer-Sammlung",
    "Common": "Gewöhnlich",
    "Uncommon": "Ungewöhnlich",
    "Rare": "Selten",
    "Ultra Rare": "Ultra Selten",
    "Legendary": "Legendär",
    "Epic": "Episch",
    "Mythic": "Mythisch",
    "First Responder": "Ersthelfer",
    "NFT Nutters Marketplace": "NFT Nutters Marktplatz",
    "Open Full Marketplace": "Vollständigen Marktplatz Öffnen",
    "The 15 Grail Cards": "Die 15 Grail-Karten",
    "NFT Rank & Utility System": "NFT Rang- und Nutzensystem",
    "Holding Requirement": "Halteanforderung",
    "Fee Reduction": "Gebührenreduzierung",
    "NFT Utility Features": "NFT-Nutzenfunktionen",
    "Diamond Hands Rewards": "Diamanthände-Belohnungen",
    "Governance Power": "Governance-Macht",
    "Exclusive Airdrops": "Exklusive Airdrops",
    "Staking Boost": "Staking-Boost",
    "Rank Promotion": "Rangbeförderung",
    "Supporting Veterans & First Responders": "Unterstützung von Veteranen und Ersthelfern",
    "NFT Development Roadmap": "NFT-Entwicklungsfahrplan",
    "In Progress": "In Bearbeitung",
    "Planned": "Geplant",
    "Future": "Zukunft",
    "Phase 1": "Phase 1",
    "Phase 2": "Phase 2",
    "Phase 3": "Phase 3",
    "Artwork & Minting": "Kunst und Prägung",
    "Utility Activation": "Nutzenaktivierung",
    "Advanced Features": "Erweiterte Funktionen",
    "PulseChain Network Stats": "PulseChain-Netzwerkstatistiken",
    "Gas Price": "Gaspreis",
    "Block Number": "Blocknummer",
    "Total Value Locked": "Gesamtwert Gesperrt",
    "24h Volume": "24h-Volumen",
    "Active Wallets": "Aktive Wallets",
    "Transactions": "Transaktionen",
    "You Pay": "Sie Zahlen",
    "You Receive": "Sie Erhalten",
    "Swap Tokens": "Token Tauschen",
    "Max": "Max",
    "Balance": "Guthaben",
    "Price Impact": "Preisauswirkung",
    "Minimum Received": "Minimum Erhalten",
    "Route": "Route",
    "Slippage": "Slippage",
    "Your Portfolio": "Ihr Portfolio",
    "Total Value": "Gesamtwert",
    "Assets": "Vermögenswerte",
    "Token": "Token",
    "Price": "Preis",
    "Amount": "Betrag",
    "Value": "Wert",
    "24h Change": "24h-Änderung",
    "Yield Farms": "Ertragsfarmen",
    "Stake": "Staken",
    "Unstake": "Entstaken",
    "Harvest": "Ernten",
    "APY": "APY",
    "TVL": "TVL",
    "Your Stake": "Ihr Stake",
    "Earned": "Verdient",
    "DCA Strategy": "DCA-Strategie",
    "Create DCA Order": "DCA-Auftrag Erstellen",
    "Frequency": "Häufigkeit",
    "Amount per Order": "Betrag pro Auftrag",
    "Total Orders": "Gesamtaufträge",
    "Active": "Aktiv",
    "Completed": "Abgeschlossen",
    "Cancelled": "Storniert",
    "Daily": "Täglich",
    "Weekly": "Wöchentlich",
    "Monthly": "Monatlich",
    "Token Distribution": "Token-Verteilung",
    "Total Supply": "Gesamtangebot",
    "Circulating Supply": "Umlaufangebot",
    "Burned": "Verbrannt",
    "Liquidity Pool": "Liquiditätspool",
    "Contract Address": "Vertragsadresse",
    "Buy Tax": "Kaufsteuer",
    "Sell Tax": "Verkaufssteuer",
    "Active Proposals": "Aktive Vorschläge",
    "Create Proposal": "Vorschlag Erstellen",
    "Vote": "Abstimmen",
    "For": "Dafür",
    "Against": "Dagegen",
    "Abstain": "Enthaltung",
    "Quorum": "Quorum",
    "Voting Power": "Stimmkraft",
    "Delegate": "Delegieren",
    "Your Delegates": "Ihre Delegierten",
    "Treasury Balance": "Schatzkammer-Saldo",
    "Latest News": "Neueste Nachrichten",
    "Read More": "Mehr Lesen",
    "Published": "Veröffentlicht",
    "Share": "Teilen",
    "Ask anything about HERO, PulseChain, or DeFi": "Fragen Sie alles über HERO, PulseChain oder DeFi",
    "Type your message...": "Nachricht eingeben...",
    "Send": "Senden",
    "Loading...": "Laden...",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Cancel": "Abbrechen",
    "Confirm": "Bestätigen",
    "Close": "Schließen",
    "Back": "Zurück",
    "Next": "Weiter",
    "Previous": "Vorherige",
    "Search": "Suchen",
    "Filter": "Filtern",
    "Sort": "Sortieren",
    "Copy": "Kopieren",
    "Copied!": "Kopiert!",
    "View All": "Alle Anzeigen",
    "Show More": "Mehr Anzeigen",
    "Show Less": "Weniger Anzeigen",
    "No results found": "Keine Ergebnisse gefunden",
    "Feature coming soon": "Funktion kommt bald",
    "VERIFIED BY SPYWOLF": "VON SPYWOLF VERIFIZIERT",
    "AUDITED": "GEPRÜFT",
    "KYC VERIFIED": "KYC VERIFIZIERT",
    "KYC": "KYC",
    "What is HERO?": "Was ist HERO?",
    "How to Buy": "Wie Kaufen",
    "Getting Started": "Erste Schritte",
    "PulseChain": "PulseChain",
    "BASE": "BASE",
  },
  pt: {
    "Swap": "Trocar",
    "Dashboard": "Painel",
    "Portfolio": "Portfólio",
    "DCA Orders": "Ordens DCA",
    "Limit Orders": "Ordens Limite",
    "Farm": "Fazenda",
    "Approvals": "Aprovações",
    "NFT Collection": "Coleção NFT",
    "Media": "Mídia",
    "Community Hub": "Centro Comunitário",
    "Explainer": "Explicação",
    "AI Assistant": "Assistente IA",
    "DAO Overview": "Visão Geral DAO",
    "Proposals": "Propostas",
    "Delegates": "Delegados",
    "Treasury": "Tesouraria",
    "Governance": "Governança",
    "Sign In": "Entrar",
    "Sign Out": "Sair",
    "Home": "Início",
    "Connect Wallet": "Conectar Carteira",
    "Toggle theme": "Alternar tema",
    "Select language": "Selecionar idioma",
    "Built for Veterans, by Veterans": "Construído para Veteranos, por Veteranos",
    "Launch App": "Abrir Aplicativo",
    "Learn More": "Saiba Mais",
    "Swap Aggregator": "Agregador de Troca",
    "Gasless Mode": "Modo Sem Gas",
    "Live Dashboard": "Painel ao Vivo",
    "DCA Engine": "Motor DCA",
    "Yield Farming": "Agricultura de Rendimento",
    "Token Approvals": "Aprovações de Tokens",
    "NFT Cards": "Cartas NFT",
    "Community": "Comunidade",
    "DAO Governance": "Governança DAO",
    "Powered by": "Desenvolvido por",
    "$HERO NFT Collection": "Coleção NFT $HERO",
    "Total Cards": "Total de Cartas",
    "Rarity Tiers": "Níveis de Raridade",
    "Categories": "Categorias",
    "Nations": "Nações",
    "Animated NFTs": "NFTs Animados",
    "Gallery": "Galeria",
    "Grail Cards": "Cartas Grail",
    "Rank System": "Sistema de Patentes",
    "Utility": "Utilidade",
    "Roadmap": "Roteiro",
    "Marketplace": "Mercado",
    "Military Rank Collection": "Coleção de Patentes Militares",
    "Common": "Comum",
    "Uncommon": "Incomum",
    "Rare": "Raro",
    "Ultra Rare": "Ultra Raro",
    "Legendary": "Lendário",
    "Epic": "Épico",
    "Mythic": "Mítico",
    "First Responder": "Socorrista",
    "NFT Nutters Marketplace": "Mercado NFT Nutters",
    "Open Full Marketplace": "Abrir Mercado Completo",
    "Loading...": "Carregando...",
    "Error": "Erro",
    "Success": "Sucesso",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Close": "Fechar",
    "Back": "Voltar",
    "Next": "Próximo",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Copy": "Copiar",
    "Copied!": "Copiado!",
    "View All": "Ver Tudo",
    "Show More": "Mostrar Mais",
    "Show Less": "Mostrar Menos",
    "No results found": "Nenhum resultado encontrado",
    "Feature coming soon": "Recurso em breve",
    "AUDITED": "AUDITADO",
    "KYC VERIFIED": "KYC VERIFICADO",
    "What is HERO?": "O que é HERO?",
    "How to Buy": "Como Comprar",
    "Getting Started": "Primeiros Passos",
  },
  ja: {
    "Swap": "スワップ",
    "Dashboard": "ダッシュボード",
    "Portfolio": "ポートフォリオ",
    "DCA Orders": "DCA注文",
    "Limit Orders": "指値注文",
    "Farm": "ファーム",
    "Approvals": "承認",
    "NFT Collection": "NFTコレクション",
    "Media": "メディア",
    "Community Hub": "コミュニティハブ",
    "Explainer": "解説",
    "AI Assistant": "AIアシスタント",
    "DAO Overview": "DAO概要",
    "Proposals": "提案",
    "Delegates": "代議員",
    "Treasury": "財務",
    "Governance": "ガバナンス",
    "Sign In": "ログイン",
    "Sign Out": "ログアウト",
    "Home": "ホーム",
    "Connect Wallet": "ウォレット接続",
    "Toggle theme": "テーマ切替",
    "Select language": "言語選択",
    "Built for Veterans, by Veterans": "退役軍人による、退役軍人のために",
    "Launch App": "アプリを起動",
    "Learn More": "詳しく見る",
    "Swap Aggregator": "スワップアグリゲーター",
    "Gasless Mode": "ガスレスモード",
    "Live Dashboard": "ライブダッシュボード",
    "DCA Engine": "DCAエンジン",
    "Yield Farming": "イールドファーミング",
    "Token Approvals": "トークン承認",
    "NFT Cards": "NFTカード",
    "Community": "コミュニティ",
    "DAO Governance": "DAOガバナンス",
    "Powered by": "提供",
    "$HERO NFT Collection": "$HERO NFTコレクション",
    "Total Cards": "総カード数",
    "Rarity Tiers": "レアリティ階層",
    "Categories": "カテゴリ",
    "Nations": "国家",
    "Animated NFTs": "アニメーションNFT",
    "Gallery": "ギャラリー",
    "Grail Cards": "グレイルカード",
    "Rank System": "ランクシステム",
    "Utility": "ユーティリティ",
    "Roadmap": "ロードマップ",
    "Marketplace": "マーケットプレイス",
    "Military Rank Collection": "軍事ランクコレクション",
    "Common": "コモン",
    "Uncommon": "アンコモン",
    "Rare": "レア",
    "Ultra Rare": "ウルトラレア",
    "Legendary": "レジェンダリー",
    "Epic": "エピック",
    "Mythic": "ミシック",
    "Loading...": "読み込み中...",
    "Error": "エラー",
    "Success": "成功",
    "Cancel": "キャンセル",
    "Confirm": "確認",
    "Close": "閉じる",
    "Back": "戻る",
    "Next": "次へ",
    "Search": "検索",
    "Filter": "フィルター",
    "Copy": "コピー",
    "Copied!": "コピー済み！",
    "View All": "すべて表示",
    "Show More": "もっと見る",
    "Show Less": "閉じる",
    "No results found": "結果が見つかりません",
    "Feature coming soon": "機能は近日公開",
    "AUDITED": "監査済み",
    "KYC VERIFIED": "KYC認証済み",
    "What is HERO?": "HEROとは？",
    "How to Buy": "購入方法",
    "Getting Started": "はじめに",
  },
  ko: {
    "Swap": "스왑",
    "Dashboard": "대시보드",
    "Portfolio": "포트폴리오",
    "DCA Orders": "DCA 주문",
    "Limit Orders": "지정가 주문",
    "Farm": "팜",
    "Approvals": "승인",
    "NFT Collection": "NFT 컬렉션",
    "Media": "미디어",
    "Community Hub": "커뮤니티 허브",
    "Explainer": "설명",
    "AI Assistant": "AI 어시스턴트",
    "DAO Overview": "DAO 개요",
    "Proposals": "제안",
    "Delegates": "대리인",
    "Treasury": "재무",
    "Governance": "거버넌스",
    "Sign In": "로그인",
    "Sign Out": "로그아웃",
    "Home": "홈",
    "Connect Wallet": "지갑 연결",
    "Toggle theme": "테마 전환",
    "Select language": "언어 선택",
    "Built for Veterans, by Veterans": "참전용사에 의한, 참전용사를 위한",
    "Launch App": "앱 시작",
    "Learn More": "더 알아보기",
    "Swap Aggregator": "스왑 애그리게이터",
    "Gasless Mode": "가스리스 모드",
    "Live Dashboard": "실시간 대시보드",
    "DCA Engine": "DCA 엔진",
    "Yield Farming": "수익 농사",
    "Token Approvals": "토큰 승인",
    "NFT Cards": "NFT 카드",
    "Community": "커뮤니티",
    "DAO Governance": "DAO 거버넌스",
    "Powered by": "제공",
    "$HERO NFT Collection": "$HERO NFT 컬렉션",
    "Total Cards": "총 카드",
    "Rarity Tiers": "희귀도 등급",
    "Categories": "카테고리",
    "Nations": "국가",
    "Animated NFTs": "애니메이션 NFT",
    "Gallery": "갤러리",
    "Grail Cards": "그레일 카드",
    "Rank System": "랭크 시스템",
    "Utility": "유틸리티",
    "Roadmap": "로드맵",
    "Marketplace": "마켓플레이스",
    "Military Rank Collection": "군사 랭크 컬렉션",
    "Common": "커먼",
    "Uncommon": "언커먼",
    "Rare": "레어",
    "Ultra Rare": "울트라 레어",
    "Legendary": "레전더리",
    "Epic": "에픽",
    "Mythic": "미식",
    "Loading...": "로딩 중...",
    "Error": "오류",
    "Success": "성공",
    "Cancel": "취소",
    "Confirm": "확인",
    "Close": "닫기",
    "Back": "뒤로",
    "Next": "다음",
    "Search": "검색",
    "Filter": "필터",
    "Copy": "복사",
    "Copied!": "복사됨!",
    "View All": "모두 보기",
    "Show More": "더 보기",
    "Show Less": "접기",
    "No results found": "결과를 찾을 수 없습니다",
    "Feature coming soon": "기능 출시 예정",
    "AUDITED": "감사 완료",
    "KYC VERIFIED": "KYC 인증됨",
    "What is HERO?": "HERO란?",
    "How to Buy": "구매 방법",
    "Getting Started": "시작하기",
  },
  zh: {
    "Swap": "兑换",
    "Dashboard": "仪表板",
    "Portfolio": "投资组合",
    "DCA Orders": "定投订单",
    "Limit Orders": "限价订单",
    "Farm": "农场",
    "Approvals": "授权",
    "NFT Collection": "NFT收藏",
    "Media": "媒体",
    "Community Hub": "社区中心",
    "Explainer": "说明",
    "AI Assistant": "AI助手",
    "DAO Overview": "DAO概览",
    "Proposals": "提案",
    "Delegates": "代表",
    "Treasury": "金库",
    "Governance": "治理",
    "Sign In": "登录",
    "Sign Out": "退出",
    "Home": "首页",
    "Connect Wallet": "连接钱包",
    "Toggle theme": "切换主题",
    "Select language": "选择语言",
    "Built for Veterans, by Veterans": "由退伍军人为退伍军人打造",
    "Launch App": "启动应用",
    "Learn More": "了解更多",
    "Swap Aggregator": "兑换聚合器",
    "Gasless Mode": "无Gas模式",
    "Live Dashboard": "实时仪表板",
    "DCA Engine": "定投引擎",
    "Yield Farming": "收益耕作",
    "Token Approvals": "代币授权",
    "NFT Cards": "NFT卡牌",
    "Community": "社区",
    "DAO Governance": "DAO治理",
    "Powered by": "技术支持",
    "$HERO NFT Collection": "$HERO NFT收藏",
    "Total Cards": "总卡牌数",
    "Rarity Tiers": "稀有度等级",
    "Categories": "类别",
    "Nations": "国家",
    "Animated NFTs": "动画NFT",
    "Gallery": "画廊",
    "Grail Cards": "圣杯卡",
    "Rank System": "军衔系统",
    "Utility": "实用功能",
    "Roadmap": "路线图",
    "Marketplace": "市场",
    "Military Rank Collection": "军衔收藏",
    "Common": "普通",
    "Uncommon": "非凡",
    "Rare": "稀有",
    "Ultra Rare": "超稀有",
    "Legendary": "传奇",
    "Epic": "史诗",
    "Mythic": "神话",
    "Loading...": "加载中...",
    "Error": "错误",
    "Success": "成功",
    "Cancel": "取消",
    "Confirm": "确认",
    "Close": "关闭",
    "Back": "返回",
    "Next": "下一步",
    "Search": "搜索",
    "Filter": "筛选",
    "Copy": "复制",
    "Copied!": "已复制！",
    "View All": "查看全部",
    "Show More": "显示更多",
    "Show Less": "收起",
    "No results found": "未找到结果",
    "Feature coming soon": "功能即将推出",
    "AUDITED": "已审计",
    "KYC VERIFIED": "KYC已验证",
    "What is HERO?": "什么是HERO？",
    "How to Buy": "如何购买",
    "Getting Started": "入门指南",
  },
  ar: {},
  hi: {},
  ru: {},
  uk: {},
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (text: string) => text,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && stored in translations) return stored as Language;
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang;
  }, []);

  // Set document lang on mount
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  // Translation function — returns translated text or falls back to original
  const t = useCallback((text: string): string => {
    if (language === 'en') return text;
    const dict = translations[language];
    if (!dict || Object.keys(dict).length === 0) {
      // For languages without dictionaries, fall back to English
      return text;
    }
    return dict[text] || text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export { STORAGE_KEY, translations };
export type { TranslationDict };
