/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20ForTesting__factory } from './MockERC20ForTesting__factory.js';
export { MockERC721ForTesting__factory } from './MockERC721ForTesting__factory.js';